#!/usr/bin/env bash
# test-inspector-templates.sh — render the inspector role's templates with
# ansible ad-hoc (no SRC, no root) and assert on the rendered content.
set -uo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
PROV="$(dirname "$HERE")"
ANSIBLE="${PROV}/.venv/bin/ansible"
TPL="${PROV}/roles/inspector/templates"
TMP="$(mktemp -d)"
trap 'rm -rf "${TMP}"' EXIT

FAIL=0
check() { local desc="$1"; shift; if "$@" >/dev/null 2>&1; then echo "ok: ${desc}"; else echo "FAIL: ${desc}"; FAIL=$((FAIL+1)); fi; }

render() { # render <template> <dest>
  "${ANSIBLE}" localhost -c local -m ansible.builtin.template \
    -a "src=${TPL}/$1 dest=$2 mode=0644" \
    -e "inspector_base_path=/inspector" \
    -e "inspector_install_dir=/opt/ddp-inspector" \
    -e "inspector_upload_max=64m" \
    -e "inspector_root=/data/vol1/ddp-inspector" \
    -e "php_fpm_sock=/run/php/php8.3-fpm.sock" \
    >/dev/null
}

render config.php.j2 "${TMP}/config.php"
check "config.php: generated header"        grep -q 'Generated by the ddp-inspector component' "${TMP}/config.php"
check "config.php: storage_root key"        grep -qF "'storage_root' => '/data/vol1/ddp-inspector'" "${TMP}/config.php"
check "config.php: base_path key"           grep -qF "'base_path' => '/inspector'" "${TMP}/config.php"
check "config.php: gocmd_bin key"           grep -qF "'gocmd_bin' => '/usr/local/bin/gocmd'" "${TMP}/config.php"
check "config.php: rclone_bin key"          grep -qF "'rclone_bin' => '/usr/local/bin/rclone'" "${TMP}/config.php"
# Amendment (Danielle, 2026-07-29): the brief's original check here was a
# no-op (`|| true` swallowed any failure). php is installed on this machine,
# so this is a REAL assertion: `php -l` must exit 0 on the rendered file.
check "config.php: parses as PHP"           php -l "${TMP}/config.php"

render nginx-location.conf.j2 "${TMP}/ddp-inspector.conf"
check "nginx: auth_request /validate"       grep -qF 'auth_request /validate;' "${TMP}/ddp-inspector.conf"
check "nginx: location prefix"              grep -qF 'location /inspector/' "${TMP}/ddp-inspector.conf"
check "nginx: fastcgi to php socket"        grep -qF 'fastcgi_pass unix:/run/php/php8.3-fpm.sock;' "${TMP}/ddp-inspector.conf"
check "nginx: alias to app public dir"      grep -qF 'alias /opt/ddp-inspector/public/;' "${TMP}/ddp-inspector.conf"
check "nginx: upload ceiling"               grep -qF 'client_max_body_size 64m;' "${TMP}/ddp-inspector.conf"
check "nginx: generated header"             grep -q 'Generated by the ddp-inspector component' "${TMP}/ddp-inspector.conf"

render 99-ddp-inspector.ini.j2 "${TMP}/99-ddp-inspector.ini"
check "php ini: upload_max_filesize"        grep -qF 'upload_max_filesize = 64m' "${TMP}/99-ddp-inspector.ini"
check "php ini: post_max_size"              grep -qF 'post_max_size = 64m' "${TMP}/99-ddp-inspector.ini"
check "php ini: memory ceiling for donations" grep -qF 'memory_limit = 512M' "${TMP}/99-ddp-inspector.ini"
check "php ini: execution time"             grep -qF 'max_execution_time = 120' "${TMP}/99-ddp-inspector.ini"

# ---- refresh systemd units ----
RTPL="${PROV}/roles/refresh/templates"
renderr() { # renderr <template> <dest>
  "${ANSIBLE}" localhost -c local -m ansible.builtin.template \
    -a "src=${RTPL}/$1 dest=$2 mode=0644" \
    -e "inspector_root=/data/vol1/ddp-inspector" \
    -e "inspector_install_dir=/opt/ddp-inspector" \
    -e "inspector_service_user=www-data" -e "inspector_service_group=www-data" \
    >/dev/null
}
renderr ddp-refresh.service.j2 "${TMP}/ddp-refresh.service"
check "service: oneshot"                    grep -qF 'Type=oneshot' "${TMP}/ddp-refresh.service"
check "service: runs as www-data"           grep -qF 'User=www-data' "${TMP}/ddp-refresh.service"
check "service: exec refresh script"        grep -qF 'ExecStart=/opt/ddp-inspector/bin/ddp-refresh.sh' "${TMP}/ddp-refresh.service"
renderr ddp-refresh.path.j2 "${TMP}/ddp-refresh.path"
check "path: watches the request flag"      grep -qF 'PathExists=/data/vol1/ddp-inspector/state/refresh-requested' "${TMP}/ddp-refresh.path"
renderr ddp-refresh.timer.j2 "${TMP}/ddp-refresh.timer"
check "timer: daily"                        grep -qF 'OnCalendar=daily' "${TMP}/ddp-refresh.timer"

echo; [ "${FAIL}" -eq 0 ] && echo "ALL PASS" || { echo "${FAIL} FAILURES"; exit 1; }
